SELECT [TFSEntityId]
      ,[IndexingUnitType]
      ,[EntityType]
      ,[IndexingUnitId]
      ,[TFSEntityAttributes]
      ,[ParentUnitId]
      ,[Properties]
      ,[AssociatedJobId]
      ,[CreatedTimeUTC]
      ,[IsDeleted]
FROM [Search].[tbl_IndexingUnit]
