SELECT [Id]
      ,[IndexingUnitId]
      ,[ChangeType]
      ,[ChangeData]
      ,[CurrentStage]
      ,[State]
      ,[AttemptCount]
      ,[Prerequisites]
      ,[CreatedTimeUTC]
      ,[LastModificationTimeUTC]
      ,[LeaseId]
FROM [Search].[tbl_IndexingUnitChangeEvent]
